# drivers/oppo_devices_list/Makefile
#
# Makefile for the oppo_devices_list driver.
#
# Copyright (C) 2004,2005 TomTom BV <http://www.tomtom.com/>
# Author: Dimitry Andric <dimitry.andric@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-y  += oppo_devices_list.o

# EOF
