/*
 * Generated by MTK SP Drv_CodeGen Version 08.01.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Wed Jan  8 01:02:58 2014
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_TEMPERATURE_CHANNEL     0


#endif //_CUST_AUXADC_TOOL_H


