/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Fri Aug 30 14:25:44 2013
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1




#define CUST_EINT_MD1_1_NAME             "MD1_SIM1_HOT_PLUG_EINT"
#define CUST_EINT_MD1_1_NUM              1
#define CUST_EINT_MD1_1_DEBOUNCE_CN      80
#define CUST_EINT_MD1_1_POLARITY         CUST_EINT_POLARITY_LOW
#define CUST_EINT_MD1_1_SENSITIVE        CUST_EINT_MD_LEVEL_SENSITIVE
#define CUST_EINT_MD1_1_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_ENABLE

#define CUST_EINT_MD1_CNT      1


